security:
    encoders:
        App\Entity\User:
          algorithm: bcrypt
          cost: 12

    providers:
        database_users:
            entity: { class: App\Entity\User }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # this firewall applies to all URLs
            pattern: ^/

            anonymous: ~

            # This allows the user to login by submitting a username and password
            # Reference: https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                check_path: login
                login_path: login
                default_target_path: home
                username_parameter: username
                password_parameter: password

            logout:
                path: logout
                target: home

    access_control:
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/painel', roles: ROLE_ADMIN }
